version: "3"
services:
  downstream-service:
    image: springio/downstream-service
    networks:
       - spring-cloud-network
    ports:
      - "8080:8080"
    depends_on:
        - upstream-service
    links:
        - upstream-service
  upstream-service:
    image: springio/upstream-service:latest
    networks:
       - spring-cloud-network
    ports:
      - "8081:8081"
networks:
  spring-cloud-network:
    driver: bridge  